document.writeln("<!--<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />等同于-->");
document.writeln("<meta charset=\"utf-8\">");
document.writeln("<!--优先使用IE最新版本和chrome，使用google chrome frame 内核，确保渲染的方式-->");
document.writeln("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge,chrome=1\">");
document.writeln("<!-- 启用360浏览器的极速模式(webkit) -->");
document.writeln("<meta name=\"renderer\" content=\"webkit\">");
document.writeln("<!-- 页面描述 -->");
document.writeln("<meta name=\"description\" content=\"心理咨询预约\"/>");
document.writeln("<!-- 页面关键词 -->");
document.writeln("<meta name=\"keywords\" content=\"文章\"/>");
document.writeln("<!-- 网页作者 -->");
document.writeln("<meta name=\"author\" content=\"Ariel, email@gmail.com\"/>");
document.writeln("<!-- 搜索引擎抓取 -->");
document.writeln("<meta name=\"robots\" content=\"index,follow\"/>");
document.writeln("<!--禁止百度转码贴广告-->");
document.writeln("<meta http-equiv=\"Cache-Control\" content=\"no-siteapp\" />");
document.writeln("<!-- 禁止数字识自动别为电话号码 -->");
document.writeln("<meta name=\"format-detection\" content=\"telephone=no\" /> ");
document.writeln("<!-- 为移动设备添加 viewport -->");
document.writeln("<meta name=\"viewport\" content=\"width=device-width,initial-scale=1.0,maximum-scale=1.0,user-scalable=0\">");
document.writeln("<!-- iOS 设备 begin -->");
document.writeln("<!-- 添加到主屏后的标题（iOS 6 新增） -->");
document.writeln("<meta name=\"apple-mobile-web-app-title\" content=\"文章\">");
document.writeln("<!-- 是否启用WebApp全屏模式，删除苹果默认的工具栏和菜单栏 -->");
document.writeln("<meta name=\"apple-mobile-web-app-capable\" content=\"yes\">");
document.writeln("<!-- 添加智能 App 广告条 Smart App Banner（iOS 6+ Safari） -->");
document.writeln("<meta name=\"apple-itunes-app\" content=\"app-id=myAppStoreID, affiliate-data=myAffiliateData, app-argument=myURL\">");
document.writeln("<!-- 设置苹果工具栏颜色 -->");
document.writeln("<meta name=\"apple-mobile-web-app-status-bar-style\" content=\"black\">");
document.writeln("<meta name=\"format-detection\" content=\"telephone=no\">");
document.writeln("<title>mobile-consult</title>");
document.writeln("<link href=\"css/header_footer.css\" rel=\"stylesheet\" type=\"text/css\" />");