document.writeln("  <div class=\'icon\'>");
document.writeln("    <div class=\"icon_back\"> <a href=\"\"><img src=\"images/icon_back.png\" width=\"19px\"></a> </div>");
document.writeln("    <div class=\"icon_share\"> <a href=\"\"><img src=\"images/icon_share.png\" width=\"15px\"></a> </div>");
document.writeln("  </div>");
document.writeln("  <div class=\"headpic\"> <img src=\"images/headphoto.jpg\" width=\"100%\" > </div>");
document.writeln("  <div class=\"pf\">");
document.writeln("    <div class=\"pinfor\">");
document.writeln("      <div class=\"pf_photo\">");
document.writeln("        <div class=\"photo_wrap\"> <img src=\"images/photo_wrap.png\" class=\"photo_back\"><img src=\"images/pf_photo.png\" alt=\"南亭的小调\" class=\"photo\"> </div>");
document.writeln("        <img src=\"images/icon_v.png\" class=\"icon_v\" >");
document.writeln("        <div class=\"lable\">");
document.writeln("          <p>InMe咨询师</p>");
document.writeln("        </div>");
document.writeln("      </div>");
document.writeln("    </div>");
document.writeln("    <div class=\"num\">");
document.writeln("      <div class=\"num_focus\">");
document.writeln("        <p class=\"number\">1546</p>");
document.writeln("        <p class=\"num_discrip\">关注</p>");
document.writeln("      </div>");
document.writeln("      <div class=\"num_fans\">");
document.writeln("        <p class=\"number\">1908</p>");
document.writeln("        <p class=\"num_discrip\">粉丝</p>");
document.writeln("      </div>");
document.writeln("    </div>");
document.writeln("  </div>");
document.writeln("  <div class=\"p_discrip\">");
document.writeln("    <div class=\"dis_word\">");
document.writeln("      <p>真诚又亲和，享受独处的时刻，对生命的旅途充满好奇，成长是我最乐于做的事情，倾听你的声音。</p>");
document.writeln("    </div>");
document.writeln("    <div class=\"dis_lables\">");
document.writeln("      <div class=\"dis_lable\">");
document.writeln("        <p>情感心理</p>");
document.writeln("      </div>");
document.writeln("      <div class=\"dis_lable\">");
document.writeln("        <p>人际关系</p>");
document.writeln("      </div>");
document.writeln("      <div class=\"dis_lable\">");
document.writeln("        <p>职场心理</p>");
document.writeln("      </div>");
document.writeln("    </div>");
document.writeln("    <div class=\"dis_more\"> <a href=\"\">更多</a> </div>");
document.writeln("  </div>");